name: Reproduce TKN Logs Hang

on:
  workflow_dispatch: # Allows manual triggering
  # push: # Uncomment to run on every push (be mindful of resource usage)
  #   branches:
  #     - main

jobs:
  reproduce-hang:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Set a reasonable timeout for the entire job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0' # Or desired kubectl version

      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 'latest'

      - name: Install tkn CLI
        run: |
          curl -LO https://github.com/tektoncd/cli/releases/download/v0.41.0/tektoncd-cli-0.41.0_Linux-64bit.deb
          sudo dpkg -i tektoncd-cli-0.41.0_Linux-64bit.deb
          rm tektoncd-cli-0.41.0_Linux-64bit.deb
          tkn version


      - name: Log in to OpenShift Cluster
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OC_SERVER_URL }}
          openshift_token: ${{ secrets.OC_TOKEN }}
          insecure_skip_tls_verify: true # Adjust as per your cluster's TLS setup, remove if not needed

      - name: Create Tekton Resources (Task, Pipeline, PipelineRun)
        run: |
          kubectl apply -f tekton/task.yaml
          kubectl apply -f tekton/pipeline.yaml
          PIPELINERUN_NAME=$(kubectl create -f tekton/pipelinerun.yaml -o jsonpath='{.metadata.name}')
          echo "PIPELINERUN_NAME=$PIPELINERUN_NAME" >> $GITHUB_ENV
          echo "Started PipelineRun: $PIPELINERUN_NAME"

      - name: Follow PipelineRun Logs
        run: |
          echo "Waiting for PipelineRun $PIPELINERUN_NAME to complete and streaming logs..."
          tkn pipelinerun logs --exit-with-pipelinerun-error -f "$PIPELINERUN_NAME"